spring:
  kafka:
    # Override Source to Localhost
    bootstrap-servers: localhost:29092

    consumer:
      properties:
        # Local Confluent Registry
        schema.registry.url: http://localhost:8081
        # Disable Auth/SSL for local
        basic.auth.credentials.source: URL

    # Override Target to Localhost
    producer:
      bootstrap-servers: localhost:29093
      properties:
        # Local Apicurio Registry
        apicurio.registry.url: http://localhost:8082/apis/registry/v2

bridge:
  target-kafka-brokers: localhost:29093